### ISSUE TITLE
Какой альтернативный путь расчета сопротивлений?

### ISSUE THREAD

**Issue by ilgridnev** [ilgridnev/infaproj#1]
Какой альтернативный путь расчета сопротивлений? https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80%D0%BD%D1%8B%D1%85_%D1%82%D0%BE%D0%BA%D0%BE%D0%B2 почему Юра сказал,  что это не подходит??

**Comment by Katancss** [comment]
> Какой альтернативный путь расчета сопротивлений? https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80%D0%BD%D1%8B%D1%85_%D1%82%D0%BE%D0%BA%D0%BE%D0%B2 почему Юра сказал, что это не подходит??

Метод контурных токов требует извлечения базисных циклов в графе, что реализуется несколько сложней, нежели метод узловых потенциалов, который к тому же является более универсальным методом
